alter table Campus drop constraint FK77DED8FFD4CF0817;
alter table CommandRestriction drop constraint FKD275ABA1DF007891;
alter table CommandRestriction drop constraint FKD275ABA164BE51B2;
alter table ConferenceCenter drop constraint FK521FCB1D4CF0817;
alter table FieldRestriction drop constraint FK4C6ADE92DF007891;
alter table FieldRestriction drop constraint FK4C6ADE9264BE51B2;
alter table Folder_items drop constraint FKD5EB30CF16A6420B;
alter table Hotel drop constraint FK42AD194D4CF0817;
alter table LoggedEvent drop constraint FK205C5618842B3C71;
alter table Restriction drop constraint FK65DBBACDF007891;
alter table Room drop constraint FK26F4FBD4CF0817;
alter table Session drop constraint FKD9891A76CFEA35DD;
alter table Session drop constraint FKD9891A764CD84E63;
alter table Symposium drop constraint FK77164354D4CF0817;
alter table Talk drop constraint FK27A8CC147B22D7;
alter table querySpecifications drop constraint FK9134C6B8A6C351E5;
alter table users drop constraint FK6A68E08DF007891;
drop table Campus;
drop table CommandRestriction;
drop table ComplexType;
drop table CompositeQuery;
drop table ConferenceCenter;
drop table FieldRestriction;
drop table Folder;
drop table Folder_items;
drop table Hotel;
drop table LoggedEvent;
drop table Restriction;
drop table Role;
drop table Room;
drop table Session;
drop table Speaker;
drop table Symposium;
drop table Talk;
drop table Venue;
drop table querySpecifications;
drop table users;
drop sequence hibernate_sequence;
create table Campus (venue_id int8 not null, primary key (venue_id));
create table CommandRestriction (restriction_id int8 not null, className varchar(255), commandName varchar(255), role_id int8, primary key (restriction_id));
create table ComplexType (clsname varchar(255) not null, primary key (clsname));
create table CompositeQuery (ID int8 not null, name varchar(255), queryType varchar(255), createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
create table ConferenceCenter (venue_id int8 not null, primary key (venue_id));
create table FieldRestriction (restriction_id int8 not null, fieldPath varchar(255), restrictionType_type varchar(255), restrictionType_code varchar(255), role_id int8, primary key (restriction_id));
create table Folder (ID int8 not null, name varchar(255), createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
create table Folder_items (folder_id int8 not null, items_type varchar(255), items_id varchar(255));
create table Hotel (venue_id int8 not null, primary key (venue_id));
create table LoggedEvent (ID int8 not null, type_type varchar(255), type_code varchar(255), msg varchar(255), longMsg text, user_id int8, className varchar(255), commandName varchar(255), object_type varchar(255), object_id int8, createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
create table Restriction (ID int8 not null, createdOn timestamp, deleted char(1), deletedOn timestamp, role_id int8, primary key (ID));
create table Role (ID int8 not null, name varchar(255) not null unique, createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
create table Room (ID int8 not null, createdOn timestamp, deleted char(1), deletedOn timestamp, name varchar(255), venue_id int8, primary key (ID));
create table Session (ID int8 not null, talk_id int8, startDate timestamp, endDate timestamp, location_id int8, createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
create table Speaker (ID int8 not null, name varchar(255), title varchar(255), photo bytea, bio text, createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
create table Symposium (ID int8 not null, createdOn timestamp, deleted char(1), deletedOn timestamp, name varchar(255), venue_id int8, primary key (ID));
create table Talk (ID int8 not null, title varchar(255), talkAbstract text, speaker_id int8, createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
create table Venue (ID int8 not null, createdOn timestamp, deleted char(1), deletedOn timestamp, name varchar(255), primary key (ID));
create table querySpecifications (compositequery_id int8 not null, fieldPath varchar(255), inequality varchar(255), type varchar(255), value varchar(255), createdOn timestamp, deleted char(1), deletedOn timestamp);
create table users (ID int8 not null, username varchar(255) not null unique, password varchar(255), locked char(1), name_salutation varchar(255), name_first varchar(255), name_middleInitial char(1), name_last varchar(255), name_suffix varchar(255), name_createdOn timestamp, name_deleted char(1), name_deletedOn timestamp, photo bytea, role_id int8, desktop text, createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
alter table Campus add constraint FK77DED8FFD4CF0817 foreign key (venue_id) references Venue;
alter table CommandRestriction add constraint FKD275ABA1DF007891 foreign key (role_id) references Role;
alter table CommandRestriction add constraint FKD275ABA164BE51B2 foreign key (restriction_id) references Restriction;
alter table ConferenceCenter add constraint FK521FCB1D4CF0817 foreign key (venue_id) references Venue;
alter table FieldRestriction add constraint FK4C6ADE92DF007891 foreign key (role_id) references Role;
alter table FieldRestriction add constraint FK4C6ADE9264BE51B2 foreign key (restriction_id) references Restriction;
alter table Folder_items add constraint FKD5EB30CF16A6420B foreign key (folder_id) references Folder;
alter table Hotel add constraint FK42AD194D4CF0817 foreign key (venue_id) references Venue;
alter table LoggedEvent add constraint FK205C5618842B3C71 foreign key (user_id) references users;
alter table Restriction add constraint FK65DBBACDF007891 foreign key (role_id) references Role;
alter table Room add constraint FK26F4FBD4CF0817 foreign key (venue_id) references Venue;
create index Session_endDate_idx on Session (endDate);
create index Session_startDate_idx on Session (startDate);
alter table Session add constraint FKD9891A76CFEA35DD foreign key (talk_id) references Talk;
alter table Session add constraint FKD9891A764CD84E63 foreign key (location_id) references Room;
alter table Symposium add constraint FK77164354D4CF0817 foreign key (venue_id) references Venue;
alter table Talk add constraint FK27A8CC147B22D7 foreign key (speaker_id) references Speaker;
alter table querySpecifications add constraint FK9134C6B8A6C351E5 foreign key (compositequery_id) references CompositeQuery;
alter table users add constraint FK6A68E08DF007891 foreign key (role_id) references Role;
create sequence hibernate_sequence;
