alter table CommandRestriction drop constraint FKD275ABA17748F97B;
alter table CommandRestriction drop constraint FKD275ABA1580AC39C;
alter table FieldRestriction drop constraint FK4C6ADE927748F97B;
alter table FieldRestriction drop constraint FK4C6ADE92580AC39C;
alter table Folder_items drop constraint FKD5EB30CF8CE80D61;
alter table LoggedEvent drop constraint FK205C56181C73BD5B;
alter table Movie drop constraint FK4714F10A7460995;
alter table Movie_Actor drop constraint FK2C3CDFE65092B48C;
alter table Movie_Actor drop constraint FK2C3CDFE681DCC982;
alter table Restriction drop constraint FK65DBBAC7748F97B;
alter table querySpecifications drop constraint FK9134C6B86C8BFABB;
alter table users drop constraint FK6A68E087748F97B;
drop table Actor;
drop table CommandRestriction;
drop table ComplexType;
drop table CompositeQuery;
drop table FieldRestriction;
drop table Folder;
drop table Folder_items;
drop table Genre;
drop table LoggedEvent;
drop table Movie;
drop table Movie_Actor;
drop table Restriction;
drop table Role;
drop table querySpecifications;
drop table users;
drop sequence hibernate_sequence;
create table Actor (ID int8 not null, name varchar(255), bio text, photo bytea, createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
create table CommandRestriction (restriction_id int8 not null, className varchar(255), commandName varchar(255), role_id int8, primary key (restriction_id));
create table ComplexType (clsname varchar(255) not null, primary key (clsname));
create table CompositeQuery (ID int8 not null, name varchar(255), queryType varchar(255), createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
create table FieldRestriction (restriction_id int8 not null, fieldPath varchar(255), restrictionType_type varchar(255), restrictionType_code varchar(255), role_id int8, primary key (restriction_id));
create table Folder (ID int8 not null, name varchar(255), createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
create table Folder_items (folder_id int8 not null, items_type varchar(255), items_id varchar(255));
create table Genre (ID int8 not null, createdOn timestamp, deleted char(1), deletedOn timestamp, name varchar(255), primary key (ID));
create table LoggedEvent (ID int8 not null, type_type varchar(255), type_code varchar(255), msg varchar(255), longMsg text, user_id int8, className varchar(255), commandName varchar(255), object_type varchar(255), object_id int8, createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
create table Movie (ID int8 not null, title varchar(255), poster bytea, description text, genre_id int8, year int4, director varchar(255), producer varchar(255), createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
create table Movie_Actor (movies_id int8 not null, actors_id int8 not null);
create table Restriction (ID int8 not null, createdOn timestamp, deleted char(1), deletedOn timestamp, role_id int8, primary key (ID));
create table Role (ID int8 not null, name varchar(255) not null unique, createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
create table querySpecifications (compositequery_id int8 not null, fieldPath varchar(255), inequality varchar(255), type varchar(255), value varchar(255), createdOn timestamp, deleted char(1), deletedOn timestamp);
create table users (ID int8 not null, username varchar(255) not null unique, password varchar(255), locked char(1), name_salutation varchar(255), name_first varchar(255), name_middleInitial char(1), name_last varchar(255), name_suffix varchar(255), name_createdOn timestamp, name_deleted char(1), name_deletedOn timestamp, photo bytea, role_id int8, desktop text, createdOn timestamp, deleted char(1), deletedOn timestamp, primary key (ID));
alter table CommandRestriction add constraint FKD275ABA17748F97B foreign key (role_id) references Role;
alter table CommandRestriction add constraint FKD275ABA1580AC39C foreign key (restriction_id) references Restriction;
alter table FieldRestriction add constraint FK4C6ADE927748F97B foreign key (role_id) references Role;
alter table FieldRestriction add constraint FK4C6ADE92580AC39C foreign key (restriction_id) references Restriction;
alter table Folder_items add constraint FKD5EB30CF8CE80D61 foreign key (folder_id) references Folder;
alter table LoggedEvent add constraint FK205C56181C73BD5B foreign key (user_id) references users;
alter table Movie add constraint FK4714F10A7460995 foreign key (genre_id) references Genre;
alter table Movie_Actor add constraint FK2C3CDFE65092B48C foreign key (actors_id) references Actor;
alter table Movie_Actor add constraint FK2C3CDFE681DCC982 foreign key (movies_id) references Movie;
alter table Restriction add constraint FK65DBBAC7748F97B foreign key (role_id) references Role;
alter table querySpecifications add constraint FK9134C6B86C8BFABB foreign key (compositequery_id) references CompositeQuery;
alter table users add constraint FK6A68E087748F97B foreign key (role_id) references Role;
create sequence hibernate_sequence;
